apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-deployment
  labels:
    app: ml-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: ml-app-pod
      app: ml-app
  template:
    metadata:
      name: ml-app-pod
      labels:
        name: ml-app-pod
        app: ml-app
    spec:
      containers:
        - name: ml-container
          image: saishivam/demo
          ports:
          - containerPort: 80