apiVersion: v1
kind: Service
metadata:
  name: ml-service
  labels:
    name: ml-service
    app: ml-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    name: ml-app-pod
    app: ml-app